version: '3.8'

services:
  task-assigner:
    build: .
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  # Optional: Add a database service for future backend integration
  # postgres:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: taskassigner
  #     POSTGRES_USER: admin
  #     POSTGRES_PASSWORD: password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

# volumes:
#   postgres_data:
